warehouse:
    resource: ../../src/Warehouse/Controller/
    type: annotation

azure:
    resource: ../../src/Azure/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
